name: ala_pos
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+9

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: 5.0.0
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  esc_pos_utils: ^1.1.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_beep: ^1.0.0
  flutter_blue_plus: ^1.2.0
  flutter_dotenv: ^5.0.2
  flutter_esc_pos_utils: ^0.1.7
  flutter_hooks: ^0.18.5
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.5.7
  flutter_secure_storage: 6.0.0
  formz: ^0.4.1
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  hooks_riverpod: ^2.0.0-dev.9
  intl: ^0.17.0
  ionicons: ^0.1.2
  json_annotation: ^4.6.0
  # lottie: ^1.4.1
  open_file: ^3.2.1
  permission_handler: ^10.0.0
  pretty_dio_logger: ^1.1.1
  primer_flutter:
    path: packages/primer_flutter
  result_type: ^0.2.0
  responsive_sizer: ^3.1.0
  share_plus: ^4.0.10
  shared_preferences: ^2.0.15
  simple_animations: ^4.0.2
  uuid: ^3.0.6

dev_dependencies:
  analyzer: '>=4.3.0 <4.4.0'
  auto_route_generator: 5.0.0
  build_runner: null
  dart_code_metrics: 4.17.1
  dependency_validator: ^3.2.2
  floor_generator: ^1.3.0
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  import_sorter: ^4.6.0
  json_serializable: ^6.3.1
  logger: null
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  very_good_performance: ^0.0.4

dependency_overrides:
  meta: ^1.7.0


# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  assets:
    enabled: true
import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/.env.production
    - assets/env/.env.emulator
    - assets/env/.env.development
    - assets/env/
    - assets/
    - assets/icon/
    - assets/images/
    - assets/images/empty/

# pub global activate rename
# pub global run rename --bundleId com.onatcipli.networkUpp
# pub global run rename --appname "Network Upp"
# rename --appname yourappname -t ios
# pub global run rename --bundleId com.example.android.app --target android
